apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-pv-claim
      containers:
      - name: minio
        volumeMounts:
        - name: data 
          mountPath: "/data"
        image: minio/minio:RELEASE.2020-02-27T00-23-05Z
        args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
          value: {{ .Values.s3_access_key }}
        - name: MINIO_SECRET_KEY
          value: {{ .Values.s3_secret_key }}
        ports:
        - containerPort: {{ .Values.port }}
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: {{ .Values.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: {{ .Values.port }}
          initialDelaySeconds: 300
          periodSeconds: 300