{{- if .Values.deployment.mars_c.enabled }}
apiVersion: v1
kind: Secret
metadata:
    name: mars-ssh-secret
    namespace: {{ .Release.Namespace }}
data:
    id_rsa: {{ .Values.deployment.mars_c.sshPrivateKey | b64enc }}
    id_rsa.pub: {{ .Values.deployment.mars_c.sshPublicKey | b64enc }}
{{- end }}