# {{- define "imagePullSecret" }}
# {{- with .Values.deployment.imageCredentials }}
# {{- printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .registry (printf "%s:%s" .username .password | b64enc) | b64enc }}
# {{- end }}
# {{- end }}

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Values.deployment.build.registry }}
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: {{ template "imagePullSecret" . }}