{{ if .Values.deployment.rabbitmq }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.deployment.rabbitmq.replicas }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values | toYaml | sha256sum }}
        date: {{ date "20060102150405" .Release.Time | quote }}
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq-pod
        image: rabbitmq:3.7
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /etc/polytope      
      volumes:
        - name: config-volume
          configMap:
            name: polytope-config
      imagePullSecrets:
        - name: polytope-registry-cred

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.rabbitmq.host }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    port: {{ .Values.deployment.rabbitmq.port }}
    targetPort: {{ .Values.deployment.rabbitmq.port }}

{{ end }}
