
{{ if .Values.deployment.redis }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-cont
        image: redis:5.0.5-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.deployment.redis.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.redis.host }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: {{ .Values.deployment.redis.port }}
    targetPort: {{ .Values.deployment.redis.port }}

{{ end }}
