{{- if .Values.seaweedfs.enabled }}
{{- if .Values.seaweedfs.filer.enabled }}
{{- if .Values.seaweedfs.filer.extraEnvironmentVars.WEED_MYSQL_ENABLED }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-seaweedfs-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  user: {{ .Values.mysql.auth.username }}
  password: {{ .Values.mysql.auth.password }}
{{- end }}
{{- end }}
{{- end }}