{{- if .Values.seaweedfs.enabled }}
{{- if .Values.seaweedfs.filer.enabled }}
{{- if .Values.seaweedfs.filer.extraEnvironmentVars.WEED_MYSQL_ENABLED }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-seaweedfs-db
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
stringData:
  user: {{ .Values.mysql.auth.username }}
  password: {{ .Values.mysql.auth.password }}
---
{{- end }}
{{- end }}
{{- end }}

{{- if .Values.seaweedfs.enabled }}
{{- if .Values.seaweedfs.createS3Secret.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.seaweedfs.createS3Secret.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    app.kubernetes.io/component: s3
stringData:
    seaweedfs_s3_config: |-
      {
        "identities": [
          {
            "name": "anvAdmin",
            "credentials": [
              {
                "accessKey": "{{ .Values.seaweedfs.filer.s3.credentials.anvAdmin.accessKey }}",
                "secretKey": "{{ .Values.seaweedfs.filer.s3.credentials.anvAdmin.secretKey }}"
              }
            ],
            "actions": ["Admin", "Read", "Write", "List"]
          },
          {
            "name": "anonymous",
            "actions": ["Read"]
          }
        ]
      }
{{- end }}
{{- end }}