##
## Copyright 2022 European Centre for Medium-Range Weather Forecasts (ECMWF)
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## In applying this licence, ECMWF does not waive the privileges and immunities
## granted to it by virtue of its status as an intergovernmental organisation nor
## does it submit to any jurisdiction.
##


{{ if .Values.testrunner }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: testrunner
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.testrunner.replicas }}
  selector:
    matchLabels:
      app: testrunner
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values | toYaml | sha256sum }}
        date: {{ date "20060102150405" .Release.Time | quote }}
      labels:
        app: testrunner
    spec:
      containers:
      - name: testrunner-pod
        {{ if .Values.deployment.fqn_images }}
        image: {{ .Values.deployment.fqn_images.polytope_common }}
        {{ else if .Values.deployment.build.tag }}
        image: {{ .Values.deployment.build.registry }}/polytope-common:{{ .Values.deployment.build.tag }}
        {{ else }}
        image: {{ .Values.deployment.build.registry }}/polytope-common:{{ .Release.Namespace }}-latest
        {{ end }}
        imagePullPolicy: Always
        volumeMounts:
          - name: config-volume
            mountPath: /etc/polytope
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POLYTOPE_PROXY
          value: {{ .Values.deployment.polytope_proxy }}
        command: ['/bin/sh']
        args: ['-c', 'tail -f /dev/null']
      volumes:
        - name: config-volume
          configMap:
            name: polytope-config
      imagePullSecrets:
        - name: polytope-registry-cred

{{ end }}
