# Ignore all by default

*

# Reinclude source

!polytope-deployment/common/*

!polytope-server/polytope_server/*
!polytope-server/tests/*
!polytope-server/MANIFEST.in
!polytope-server/requirements.txt
!polytope-server/setup.py
!polytope-mars
!fdb5
!fdbremote
!polytope
!covjsonkit
!polytope-config/auxiliary

# apply normal rules on top of that

**/*.swp
**/*.py[cod]
**/__pycache__/
.gitignore
